### ISSUE TITLE
Add oauth2 flow for third party devices.

### ISSUE THREAD

**Issue by lazylazyllama** [mozilla-iot/gateway#2568] opened 2020-08-04 12:16 UTC
I would like to write an app which is able to connect to my gateway via oauth2.

But right now I don't really see a way to do that in a simple way. With simple I mean, that I would like my app to be redirected to the login page of the webthings gateway. Then I would like to fill in my credentials and get a token and a refresh token being send to my app.

Or even greater would be if you would implement the "Resource Owner Password Credentials" flow. This way it would be possible to stay inside the app and not being redirected to the browser.

**Comment by mrstegeman** [comment] 2020-08-04 16:22
Duplicate of #340

**Closed by mrstegeman** 2020-08-04 16:22 UTC
