### ISSUE TITLE
Custom UI link doesn't appear when the href is a relative url

### ISSUE THREAD

**Issue by chris-zen** [mozilla-iot/gateway#1293] opened 2018-08-23 21:56 UTC
I am building a WebThing using the Framework. I also developed my custom UI using React. I tried to specify the custom UI in the Thing using a relative url (`/index.html`), but the Gateway doesn't show the link as expected according to [this doc](https://docs.google.com/presentation/d/1rMeg6hep8JQflqwbiNIbhSoK9StCeVZ2npphmQHKda4/edit#slide=id.g3b5aa6b68a_1_58).

This is how I set the UI HRef:

```javascript
class ThermostatThing extends Thing {
  constructor() {
    super('Thermostat', 'Thermostat', 'Thermostat Thing');
    this.setUiHref('/index.html');
    // ...
  }
}
```

This is how I start the server to be able to serve the `index.html`:

```javascript
const thermostatThing = new ThermostatThing();
const server = new WebThingServer(new SingleThing(thermostatThing), 8888);
server.app.use(express.static('public'));
// ...
```

And this is the relevant part of the links that is generated:

```json
"links": [
    {
      "rel": "alternate",
      "mediaType": "text/html",
      "href": "/index.html"
    }
  ]
```

Passing an absolute url solved the problem. But for a thing server it's not trivial to guess its own base url (as it depends on how it has been deployed). The gateway has this information through the `thing-url-adapter`, and could use it to compose an absolute url.

Some more context [here](https://discourse.mozilla.org/t/custom-ui-for-a-webthing-not-working-as-expected/31085).

**Comment by mrstegeman** [comment] 2018-08-27 17:43
@chris-zen I'm unable to reproduce this. Here's what I did:

Modify `example/single-thing.js` from webthing-node as such:
1. Add `const express = require('express');` at the top.
2. Add `thing.setUiHref('/index.html');` inside `makeThing()`, after `const thing = ...`.
3. Add `server.app.use(express.static('public'));` inside `runServer()`, after `const server = ...`.
4. Create  `public` directory inside `webthing-node` (at the same level as `example`).
5. Add a basic `index.html` inside `public`.
6. Run example.

The link icon shows up for me in the gateway's UI, and its `href` contains the full URL, not relative.

**Comment by mrstegeman** [comment] 2018-10-15 13:00
@chris-zen Can you confirm whether or not this is indeed still an issue?

**Comment by chris-zen** [comment] 2018-10-29 18:10
Sorry, vacations finished and my focus went into other unrelated projects since then. I might need more time to revisit this, sorry. Feel free to close.

**Comment by mrstegeman** [comment] 2018-10-29 18:32
@chris-zen No problem. I'll close the issue for now, but please re-open if you can still reproduce.

**Closed by mrstegeman** 2018-10-29 18:32 UTC
Labels: backlog, bug
