### ISSUE TITLE
Removing an item may leaving adapter in bad state

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#2134] opened 2019-09-06 15:38 UTC
The gateway may call removeThing and then if the user doesn't actually remove something, it never winds up calling cancelRemoveThing

For example, the user may click on Remove, but then not press the action button on a zwave device and just hit the back button.

I think that removing a device should have a timeout similar to adding a device so that the adapter can ensure that the remove process is either completed or cancelled.

**Comment by mrstegeman** [comment] 2019-09-06 15:41
Duplicate of #1930

**Closed** 2019-09-09 17:14 UTC
Labels: duplicate
