### ISSUE TITLE
Multiple Trigger in rule engine

### ISSUE THREAD

**Issue by xAlban** [mozilla-iot/gateway#1028] opened 2018-05-23 13:29 UTC
When I saw the implementation of Multi Effect, I wondered if someone is trying to implement a Multi Trigger aswell.
For exemple: if time > 8PM and/or light is OFF, then we turn all the lights on

I'm aware that we need to implement aswell a kind of logic between the triggers but I think it's a fonctionnality that is interesting to implement.

**Comment by mrstegeman** [comment] 2018-05-23 13:33
Duplicate of #773

**Closed by mrstegeman** 2018-05-23 13:33 UTC
Labels: rules-engine
