### ISSUE TITLE
The 'things' table can't be found

### ISSUE THREAD

**Issue by andrenatal** [mozilla-iot/gateway#49] opened 2017-04-26 23:41 UTC
When I try to add a new device, I am seeing the following error in the node app. I can see the device listed in the website, but seems it's not being stored in the database, because doesn't appear in the main page (keeps showing a 'No devices yet.' message)

 ```
ZWave: node2 valueAdded: 50:Previous Reading -> 0.025
ZWave: node2 valueAdded: 50:Interval -> 70
Adapter: FooAdapter id Foo1 pairing cancelled
AdapterManager: About to resolve deferredAdd
Deferred: Resolving deferred promise id: 1 arg: { id: 'zwave-da95d8e6-2',
  name: 'zwave-da95d8e6-2-Switch',
  type: 'onOffSwitch',
  properties: [ { name: 'on', type: 'boolean' } ] }
Error saving new thing Error: SQLITE_ERROR: no such table: things
```

**Comment by dhylands** [comment] 2017-05-03 00:53
I've had this reported by others as well. I think it happens if the app.js crashes at the wrong time, before the database is completely written out to disk. It seems to happen commonly if one of the dependencies is missing.

I think that the fix is to make sure that we do a flush to disk after creating the tables. This might be as simple as closing and re-opening the database.

**Comment by dhylands** [comment] 2017-05-03 00:54
A workaround is to do the following:
- quit the node server (app.js)
- remove the db.sqlite3 file
- restart the node server.

**Comment by benfrancis** [comment] 2017-05-12 15:06
I may have found some STR:
* Run "node app.js"
* Remove db.sqlite3
* Start a new terminal and run "node app.js"

The second instance will try to re-create the database but will error because the TCP port is already in use, leaving the database half created.

**Comment by dhylands** [comment] 2017-05-13 01:27
I was also seeing it where one of the dependencies was failing. It would wind up with a zero sized db.sqlite3 file.

**Comment by dhylands** [comment] 2017-06-14 01:49
Another way to reproduce:
* remove db,sqlite3
* rename libopenzwave.so to something else
* run app.js

This will create a zero sized db.sqlite3. If you then rename libopenzwave.so and relaunch then it will fail to populate the database.

**Comment by hobinjk** [comment] 2017-10-24 17:05
All tables are now created if they don't exist so this behavior should no longer occur. I tested by creating a 0-sized db.sqlite3 file and restarting the gateway

**Closed by hobinjk** 2017-10-24 17:05 UTC
Labels: bug
