### ISSUE TITLE
No way to choose a dongle for pairing when using multiple dongles

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#398] opened 2017-11-07 17:16 UTC
Under the current system, if there are multiple ZWave or ZigBee dongles connected to the gateway, then all of them will be put into pairing mode when pressing '+'.

This means that a device will pair randomly with one dongle or the other. We really need a mechanism to allow just one dongle to enter pairing mode.

This could be an adapter setting, or could be something in the pairing screen.

**Comment by benfrancis** [comment] 2017-11-08 10:52
Hmm, I don't think this is worth complicating the UI for given I expect it to be very rare that someone would have two controllers for the same protocol plugged into the same gateway. On consumer hardware I expect it would never happen.

I don't see any harm in a configuration parameter to set one dongle as the master one, but probably not a high priority.

**Comment by mrstegeman** [comment] 2018-08-30 15:38
This should be possible with #421. If not, then this is a duplicate of #197.

**Closed by mrstegeman** 2018-08-30 15:38 UTC
