### ISSUE TITLE
MaxListenersExceededWarnings

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-iot/gateway#1128] opened 2018-06-25 13:10 UTC
I'm getting some warnings from the node EventEmitter when running the gateway with a couple of devices set up:
```
(node:7883) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 propertyChanged listeners added. Use emitter.setMaxListeners() to increase limit
(node:7883) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 actionStatus listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by mrstegeman** [comment] 2018-06-25 13:13
Duplicate of #561

**Comment by sogaani** [comment] 2018-06-25 13:23
@mrstegeman This is not same as #561.
#561 is issue about client side memory leak. This is about server side issue.
`EventEmitter` has limitation for listening event and report warning when over limitation. However it is just warning and not errors. We can use `setMaxListeners` API to avoid this warning.

**Comment by sogaani** [comment] 2018-06-25 13:30
Default `setMaxListeners`  is 10. If an user has more than 10 devices, he get warning even if fixed client side issue. 
Perhaps we need https://github.com/mozilla-iot/gateway/issues/947 too.

**Comment by mrstegeman** [comment] 2018-06-25 13:32
That's true. We should increase the number of listeners as well. I'll re-open this issue for that purpose.

**Comment by rzr** [comment] 2019-02-28 15:19
Observed this too, I suspect this is also slowing down on startup.

**Comment by flatsiedatsie** [comment] 2019-05-09 19:21
I come across this 'issue' too in my logs.

```
2019-05-09 19:16:38.004 ERROR  : (node:27104) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 actionStatus listeners added. Use emitter.setMaxListeners() to increase limit
```

**Comment by flatsiedatsie** [comment] 2019-06-03 08:22
And it's here too: https://forum.mysensors.org/topic/10435/mysensors-add-on-crashed/5

**Comment by mrstegeman** [comment] 2019-12-26 19:53
Increasing the number of listeners just seems pointless. Somebody will always hit the max, regardless of what we set.

**Closed by mrstegeman** 2019-12-26 19:53 UTC
