### ISSUE TITLE
Set the main sensor from a multi-level sensor

### ISSUE THREAD

**Issue by dan1elhughes** [mozilla-iot/gateway#2431] opened 2020-02-12 23:42 UTC
When I add a multi-level sensor, one of my two levels (temperature and humidity) gets selected as the "main" one on the main page. I'd like to be able to select which is the main one. 😸

**Comment by mrstegeman** [comment] 2020-02-12 23:56
Duplicate of #1826

**Closed by mrstegeman** 2020-02-12 23:56 UTC
