### ISSUE TITLE
"if" vs "while", for time based rules

### ISSUE THREAD

**Issue by twobraids** [mozilla-iot/gateway#1232] opened 2018-07-31 21:35 UTC
The default for "if/while" is "while".  If a time Thing is dropped onto the predicate half of a rule, then the rule reads "while the time is (time), turn (thing) on".   "While" is a tough concept for a point in time.   Is it possible to have it default to "if" if time is involved in the predicate?  

Using "while" right now appears to set a timer for about ten seconds at the designated time.

**Comment by benfrancis** [comment] 2018-08-01 09:43
I agree with this. @hobinjk's point was that while is a better default for anything except time. But I do think that while as a default leads to unexpected behaviour for timers.

I think we either need to change the default to "if" everywhere (which means boolean logic doesn't automatically reverse by default for other types of inputs), or somehow make timers a special case where "if" is the default if you haven't already chosen between "while" and "if".

Also, it would be nice that the "while" lasted for the full minute rather than an arbitrary few seconds before the rules engine realises it's no longer exactly that time any more. That would make more sense.

**Comment by benfrancis** [comment] 2018-08-01 09:44
I'm going to assign this to 0.5, but if we don't figure out what to do by then then this can come in a bugfix release.

**Comment by hobinjk** [comment] 2018-08-01 14:26
The main thing I could do here is flip the time trigger back to the way it used to work where even if it's used in a 'while' rule it behaves as if it were in an 'if' rule.

Unfortunately, this would break logic like "if it's 8pm and I'm not home then turn on the light"

I think the best solution is to extend the activation of the time trigger to 1 minute so that it's slightly more clear that the implementation is being a pedantic rules lawyer. I could also add an "exactly" to the summary of the while rule, i.e. "while I'm not home and it's exactly 8pm then turn on the light"

**Comment by benfrancis** [comment] 2018-08-08 12:04
I agree that the time trigger should be extended to 1 minute when "while" is selected so that it behaves more logically.

I also agree that for the time trigger "if" would be a better default. Can we change that specifically for time triggers, or does that become too complex (e.g. when multiple inputs are selected)?

**Comment by hobinjk** [comment] 2018-08-08 19:39
In my opinion automatically changing would be too complex and unpredictable, especially since adding another input to the rule would have the effect of changing the rule type and "revealing" the implementation of the time trigger.

I think it's much better to allow people to experiment with the time trigger, figure out its exact behavior, then use that behavior in consistently-defined rules that don't flip around unexpectedly.

**Comment by twobraids** [comment] 2018-08-08 21:14
this could become a feature, not a bug.

How about change the clock object to have both a time point and a duration.  The duration is used along with the time point only in "while" predicates.  "If" predicates only pay attention to the time point.

The rule text could read "while the time is within 1 hour after 3:00pm..." or "if the time is exactly 3:00pm.

In the end, the current behavior doesn't change much (just the default while time and the rule text) and the user gets a powerful new feature.

**Comment by benfrancis** [comment] 2018-08-10 16:32
@hobinjk wrote:
> I could also add an "exactly" to the summary of the while rule, i.e. "while I'm not home and it's exactly 8pm then turn on the light"

That sounds potentially confusing. Arguably 20:00:01 is not exactly 8pm.

> How about change the clock object to have both a time point and a duration?

The fact that duration would have no effect if "if" is selected seems confusing, plus the additional complexity of having two time fields.

Making the time input last the full minute for while conditionals seems like a good start.

I'm still wondering whether "if" is a better global default than "while". How does IFTTT deal with this?

**Comment by hobinjk** [comment] 2018-08-10 16:42
IFTTT does it arbitrarily based on the intent of the person who wrote the applet. For example, "if I receive a phone call pulse my hue lights" and "if it's after 9pm turn off my lights" use the same terminology but are functionally different.

Additionally the IFTTT style of construction only allows for one "this" and one "that" so they will never run into our problems of mixing trigger/effect types

**Comment by benfrancis** [comment] 2018-08-23 20:27
I'm thinking we should change the global default to "if".

Arguments for and against?

**Comment by hobinjk** [comment] 2018-08-23 20:44
Against:
- Light-type rules will be a little strange
- It's not what it was before
For:
- It's what people seem to expect
- Works well with time rules
- Switching to "while" is a more natural upgrade, "switch to while when you want to simplify rules" whereas switching to "if" is "switch to if when your time/event-based rule just doesn't work"

All in all I agree that switching to default to "if" is a good idea.

**Comment by benfrancis** [comment] 2018-10-02 15:42
@hobinjk Didn't this already land on 0.5.x?

**Comment by hobinjk** [comment] 2018-10-02 15:44
Yes, the switching to default "if" landed

**Closed** 2018-10-02 15:57 UTC
Labels: next, rules-engine, task
