### ISSUE TITLE
Time Triggers should internationalize time properly

### ISSUE THREAD

**Issue by hobinjk** [mozilla-iot/gateway#563] opened 2018-01-29 19:15 UTC
As an easily confused American, I want to see the time described as 11:00 AM or 1:00 PM by time triggers to match the time input in my locale.

Although honestly 24-hour time just makes more sense

**Comment by mrstegeman** [comment] 2019-10-18 18:49
Duplicate of #675

**Closed by mrstegeman** 2019-10-18 18:49 UTC
Labels: rules-engine, story
