### ISSUE TITLE
Request Action returns "No action name provided"

### ISSUE THREAD

**Issue by gerritanne** [mozilla-iot/gateway#799] opened 2018-03-24 08:31 UTC
I'm testing the Web Thing REST API, and I'm able to change properties (on/ff, level, etc). However, when I want to post an Action (to fade a bulb) I get a "No action name provided response" (I've fetched the example from the Web Things REST API document). Please find below a screenshot of my POST request.

![image](https://user-images.githubusercontent.com/36508059/37861960-ba365bb4-2f45-11e8-8d9d-e77ce28e7790.png)

Any pointers to what I might be doing wrong here?

**Comment by sogaani** [comment] 2018-03-24 08:40
We are in developing actions and events supports.

If you want to know the progress you could observe #717 .

**Comment by gerritanne** [comment] 2018-03-24 08:53
Sogaani,

Thanks for your reply. Will keep track of #717.

**Comment by mrstegeman** [comment] 2018-03-24 13:35
Duplicate of #717

**Closed by mrstegeman** 2018-03-24 13:35 UTC
