### ISSUE TITLE
Can't add Razberry module 

### ISSUE THREAD

**Issue by inteldon** [mozilla-iot/gateway#2503] opened 2020-05-30 20:26 UTC
I bought a [razberry module](https://z-wave.me/products/razberry/) and tried using it with the Mozilla Gateway and it didn't work. I tried to tweak the code and see if I could use pins 15/16 (Tx/Rx) on the raspberry pi to communicate with the ZWave chip on board using Serial API. I found no instances of zwave calls or serial commands that were being executed that I could work with. 

Has anyone tried this? Can someone point me to where those files (ZWave serial API) are being used? Is there a better way to do this? 

Thanks

**Comment by mrstegeman** [comment] 2020-05-30 20:35
Duplicate of mozilla-iot/zwave-adapter#8

**Closed by mrstegeman** 2020-05-30 20:35 UTC
