### ISSUE TITLE
Logging Into Gateway

### ISSUE THREAD

**Issue by eanmikale** [mozilla-iot/gateway#1432] opened 2018-10-19 21:48 UTC
Would like to know how to reset and/or retrieve password, as such a request would be very common among clients and prospective customers.

**Comment by dhylands** [comment] 2018-10-19 23:37
I'm not sure if this is the easiest way, but I tested it and it works. @mrstegeman would know if there is a better way. There is no way to retrieve the password (we don't store it). You can however delete the user and thus trigger a new one to be created.

1 - login to the gateway using one of the methods described here: https://github.com/mozilla-iot/wiki/wiki/Logging-into-the-Raspberry-Pi
2 - cd into the `/home/pi/.mozilla-iot/config` directory. You should see a db.sqlite3 file there.
3 - Run the command: `sqlite3 sb.sqlite3`
4 - Show the contents of the user database: `.dump users`
5 - Delete the one and only user: `delete from users where id = 1;`
6 - Verify that the user is gone
7 - From the browser, choose logout from the menu (top left)
8 - Do a hard refresh
9 - This should prompt you to create a new user/email/password.

**Comment by mrstegeman** [comment] 2018-10-20 14:13
Duplicate of #95

**Closed by mrstegeman** 2018-10-20 14:13 UTC

**Comment by eanmikale** [comment] 2018-10-20 14:48
Is it possible to request a password retrieval option during login n the next release? We are currently integrating this into courses, and our students have a lot of different platforms to login. We ran into this problem during training. The feature would help a lot when working at scale. Thanks again.
