### ISSUE TITLE
when browser view is stale, state changes affected by rules don't show in browser page even though they work

### ISSUE THREAD

**Issue by kgiori** [mozilla-iot/gateway#1360] opened 2018-09-20 18:24 UTC
steps to reproduce:
1. create a rule with virtual light "on" turns on a real LED (in my case 8 LEDs - Blinkt!)
1a. similarly, rule of change virtual light color to red turns each of 8 LEDs to a color of the rainbow.
2. the rules work fine.
3. go away for coffee, lunch, or a while (I'm not sure how long).
4. turn on virtual light, see all eight LEDs turn on (per rule), but no status change in browser page. That is, the on/off rule works for real state changes, just not browser state changes. Same problem for color change to red causing rainbow -- works for real, but no change visible in browser.
5. click refresh button on browser. repeat check of step 4 for the two rules but this time they work --   both real and browser states are correct. 
6. repeat step 3 and you see the problem again.

when not working, console F12 showed lots of wss:... errors.

**Comment by hobinjk** [comment] 2018-09-21 20:04
I'm unable to reproduce this locally. I also manually dropped websocket connections (causing a bunch of wss errors) and the gateway ui was able to reopen them and show state changes after a brief delay. 

It's possible that over a long enough time period the wsBackoff period gets to the point where it won't reopen soon enough so I'll add a limit to that and see if it helps this behavior.

**Comment by hobinjk** [comment] 2018-09-26 15:42
This should be fixed by #1363, feel free to reopen if it continues happening

**Closed by hobinjk** 2018-09-26 15:42 UTC
Labels: bug, in progress
