### ISSUE TITLE
suggestion: sign up for remote access later

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#2052] opened 2019-07-27 22:16 UTC
If you skip the creation of a Mozilla domain name during setup, it seems there is no way to reverse that decision later?

I was hoping for a button that would allow for that here:
![remote-access](https://user-images.githubusercontent.com/805405/61999958-f22e3c00-b0bb-11e9-87c3-ce9898c9e9a2.png)

I might be overlooking it.

Perhaps related to
`Settings - Enable/disable remote access`
https://github.com/mozilla-iot/gateway/issues/1051

**Comment by mrstegeman** [comment] 2019-07-27 22:33
Yes, this is a duplicate of that issue.

**Closed by mrstegeman** 2019-07-27 22:33 UTC

**Comment by flatsiedatsie** [comment] 2019-07-29 10:38
Ah, I thought that one was about toggling it on or off after it has already been set up.
