### ISSUE TITLE
Internal log "ERROR  : WebSocket sendMessage failed: Error: WebSocket is not open: readyState 2 (CLOSING)"

### ISSUE THREAD

**Issue by madb1lly** [mozilla-iot/gateway#2585] opened 2020-09-04 13:17 UTC
Hi everyone,

Everytime I load the Gateway UI, after all the entries relating to getting the latest property values etc, I get several of these messages:
```
2020-09-04 15:00:52.819 ERROR  : WebSocket sendMessage failed: Error: WebSocket is not open: readyState 2 (CLOSING)
```
The quantity of these messages is always different but there are always many of them (10-20).

Any idea what is causing this or how to debug it? Could it be the cause of the Gateway UI slowdown which I experience?

Cheers 🙂

**Comment by mrstegeman** [comment] 2020-09-04 15:58
Duplicate of #2367

**Closed by mrstegeman** 2020-09-04 15:58 UTC

**Comment by madb1lly** [comment] 2020-09-05 08:37
Hi @mrstegeman,
I did see that issue but wasn't sure if it was really the same based only on error message. Anyway let's see. 
Cheers 🙂
