### ISSUE TITLE
Addons list doesn't scroll

### ISSUE THREAD

**Issue by keton** [mozilla-iot/gateway#1342] opened 2018-09-07 16:23 UTC
under gateway.local/settings/addons/discovered there's long list of plugins that can be installed. It's much longer than single screen but doesn't scroll at least on up to date Chrome and Edge on Windows 10. It works on Firefox on Ubuntu 18.04.

PS. same is true for other long lists (i.e. things)

**Comment by mrstegeman** [comment] 2018-09-07 16:28
Fixed by #1326

**Closed by mrstegeman** 2018-09-07 16:28 UTC

**Comment by flatsiedatsie** [comment] 2019-12-02 12:55
I am routine encountering a similar issue where the add-ons list / add-addons-list scrolling freezes for a while. Possibly related to: https://github.com/mozilla-iot/gateway/issues/1290

**Comment by createcandle** [comment] 2019-12-17 11:03
It mostly seems to happen on Chromium.

**Comment by mrstegeman** [comment] 2019-12-18 22:59
@flatsiedatsie The only "freeze" I'm able to reproduce is as such:
* Open site in Chrome and navigate to Add-on settings
* Scroll all the way to the bottom
* Keep trying to scroll down for a few seconds
* Try to scroll back up
* UI freezes for a second and dumps the following message to the console:

  `This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!`

The same issue does not occur on Firefox (Nightly or Stable), and the message that gets dumped out by Chrome is nonsense, because we don't use any scrolling effects.

**Comment by mrstegeman** [comment] 2019-12-18 23:02
Profiling in Chrome shows a freeze in "Rasterize Paint" across 4 threads, which seems to point to a Chrome issue.

**Comment by flatsiedatsie** [comment] 2019-12-18 23:15
For me it happens in multiple ways:
- It freezes after one second of opening the add-ons page (so I try to scroll very quickly to the position I need, but this doesn't always work.
- After a while (10 seconds) the page becomes responsive again.
- Then it can randomly freeze again.

It happens on the add-ons page and the add-addons page.

I've tested if it still happens if I disable add-ons like the square theme. It still occurs.

Here is the add-ons page, from page load until 1 second after freezing starts:
![gateway-freeze](https://user-images.githubusercontent.com/805405/71131274-7fe9ff80-21f4-11ea-9b9c-6336359a8412.png)

Here is a recording that was started while the add-addons page was frozen. It indicats the scroll command is detected, but the page doesn't scroll.
![gateway-freeze2](https://user-images.githubusercontent.com/805405/71131301-98f2b080-21f4-11ea-94d0-0f86ffd97cee.png)

**Comment by mrstegeman** [comment] 2019-12-18 23:22
* What version of Chrome/Chromium, what platform?
* Please disable all extension add-ons and do a hard refresh of the UI.

**Comment by flatsiedatsie** [comment] 2019-12-18 23:34
Chromium for Mac (privacy friendly version, with the Google phone-home parts stripped). Version 78.0.3904.97 (Official Build) (64-bit)

I also noticed that it's mentioning 'rasterize paint' during the freeze, and that hitting the top or bottom of the page triggers it too.

Disabling all the add-ons and clearing the browser cache did not help. (Disabling Voco still crashes the Gateway, but that's probaby not related)

**Comment by flatsiedatsie** [comment] 2019-12-18 23:43
Disabling `transform: translate(0%, -50%);` on `.settings-section` makes the scroll smooth as butter, and all scrolling issues disappear.

**Comment by mrstegeman** [comment] 2019-12-19 17:26
Doing so causes this to happen:

![Screenshot_2019-12-19 WebThings Gateway](https://user-images.githubusercontent.com/457381/71194886-41c2ff00-2239-11ea-9071-2a668df9b4d8.png)

**Comment by flatsiedatsie** [comment] 2019-12-20 11:14
Yes, but that's easy to fix. 

The goal is to have things vertically centered, and there are multiple ways to do that with CSS. My recommendation: switch to [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) instead.

**Comment by flatsiedatsie** [comment] 2019-12-20 11:15
It would also solve another issue with the current technique, which is that at the moment if you have a small landscape screen (letterbox), then content falls of the top and bottom edge of the display.

**Comment by mrstegeman** [comment] 2019-12-20 19:23
I'm still convinced this is just a Chrome bug, not really an issue with our CSS. What's to say the same problem won't exist if we switched to flexbox?

What's that about things falling off the top and bottom? Do you have a screenshot or video to demonstrate?

**Comment by flatsiedatsie** [comment] 2019-12-20 22:34
> What's to say the same problem won't exist if we switched to flexbox?

Well, I tried it in the square theme :-)

> content falls of the top and bottom edge of the display

This happened sometimes during the development of addons that extend the UI, so it's not an issue with the gateway as such. Tall content would not scroll properly if it was taller than the window height. In the end I found a way to modify the CSS to keep if from happening.
