### ISSUE TITLE
gateway fails to start with no network

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#2103] opened 2019-08-23 21:09 UTC
I tried to start the gateway on my laptop when there was no internet connected and I got the following error:
```
2019-08-23 14:05:17.168 INFO   : Checking for add-on updates...
2019-08-23 14:05:17.200 ERROR  : Failed to parse add-on list.
2019-08-23 14:05:17.237 DEBUG  : mDNS error: Error: send ENETUNREACH 224.0.0.251:5353
2019-08-23 14:05:17.737 DEBUG  : mDNS error: Error: Timed out getting default route
2019-08-23 14:05:17.741 ERROR  : Error: send ENETUNREACH 224.0.0.251:5353
    at SendWrap.afterSend [as oncomplete] (dgram.js:499:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webthings-gateway@0.9.2 start: `webpack --display errors-only && node build/gateway.js "-d"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webthings-gateway@0.9.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dhylands/.npm/_logs/2019-08-23T21_05_17_779Z-debug.log
```

**Comment by mrstegeman** [comment] 2019-08-23 21:12
Duplicate of #2006

**Closed by mrstegeman** 2019-08-23 21:12 UTC
