### ISSUE TITLE
Tunnel registration is failing under OpenWRT

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1879] opened 2019-05-15 22:03 UTC
I was testing a new image using OpenWRT and I'm gettng the following error:
```
2019-05-15 11:41:27.768 INFO   : Stopping Router Setup
2019-05-15 11:41:27.774 INFO   : HTTP server listening on port 8080
2019-05-15 11:41:38.081 INFO   : Checking for add-on updates...
2019-05-15 11:41:43.191 ERROR  : Failed to parse add-on list.
2019-05-15 11:42:36.828 ERROR  : Failed to subscribe: { FetchError: request to https://api.mozilla-iot.org:8443/subscribe?name=dhylands-openwrt2&email=dhylands@gmail.com failed, reason: getaddrinfo EAI_AGAIN api.mozilla-iot.org:8443
    at ClientRequest.<anonymous> (/opt/mozilla-iot/gateway/node_modules/node-fetch/lib/index.js:1453:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  message: 'request to https://api.mozilla-iot.org:8443/subscribe?name=dhylands-openwrt2&email=dhylands@gmail.com failed, reason: getaddrinfo EAI_AGAIN api.mozilla-iot.org:8443',
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN' }
```

**Comment by dhylands** [comment] 2019-05-15 22:05
It turns out I didn't have an ethernet address (i.e. no cable plugged in). We should probably detect this and display a better error message to the user.

**Comment by benfrancis** [comment] 2019-09-02 18:34
Haha, I've done this too. Duplicate of #1936

**Closed by benfrancis** 2019-09-02 18:34 UTC
