### ISSUE TITLE
Rules with Multiple Conditions

### ISSUE THREAD

**Issue by damooooooooooh** [mozilla-iot/gateway#2216] opened 2019-10-10 18:19 UTC
I want to create a rule that sets a Day Alarm.  I have a virtual On/Off to "turn on" the alarm and I want to create a rule as follows:

```
If (DayAlarmOnOffSwitch Is On) AND (DoorContact1 Is Open OR DoorContact2 Is Open OR DoorContact3 Is Open) Then
    Alarm1.Trigger()
End
```

I can't seem to do this, I can only create a rule with all conditions = AND or OR.
To achieve the above I have to use a combination of Rules, Virtual Switches and Pulse Switch adapter.

Example below
![image](https://user-images.githubusercontent.com/1326094/66595884-c6d3cd00-eb93-11e9-8a21-606910eaa088.png)

**Comment by mrstegeman** [comment] 2019-10-10 19:17
Duplicate of #2190

**Closed by mrstegeman** 2019-10-10 19:17 UTC
Labels: duplicate

**Comment by mrstegeman** [comment] 2019-10-10 19:19
What you want could be achieved by breaking your rule down into 3 simpler rules:

```
If (DayAlarmOnOffSwitch Is On AND DoorContact1 Is Open) Then
    Alarm1.Trigger()
End
```

```
If (DayAlarmOnOffSwitch Is On AND DoorContact2 Is Open) Then
    Alarm1.Trigger()
End
```

```
If (DayAlarmOnOffSwitch Is On AND DoorContact3 Is Open) Then
    Alarm1.Trigger()
End
```
