### ISSUE TITLE
Rules - add checkbox to also add inverted rule

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1864] opened 2019-05-07 13:45 UTC
I may have a situation like this:

- If the temperature reaches 25 degrees, I'd like to turn on a disco light, to celebrate that summer is here.

But I'd also like the opposite:
- If the temperature dips below 25 degrees, turn off the disco light off again.

As far as I'm aware I would currently have to create two rules to enable this?

How about adding a little checkbox to 'also enable the opposite rule'? 

Reasons this might be a good idea:
- Less rules in the interface.
- Quickly make 'two' rules in one swoop.
- Common use case.

Reasons this might be a bad idea:
- This might only work on very simple rules / should only be possible on very basic rules.
- Complicates things.

See also the idea to quickly clone rules:
https://github.com/mozilla-iot/gateway/issues/1164

**Comment by benfrancis** [comment] 2019-05-07 14:50
@flatsiedatsie If I understand correctly, you should be able to achieve this by choosing "while" instead of "if" in the dropdown when creating the rule.

Does this work for you?

**Comment by flatsiedatsie** [comment] 2019-05-08 15:05
I tested it, and you're right, it works! It's quite elegant.

I didn't realize that the IF was a drop down. Perhaps it could visually look more like a button? It also explains why `then` is not part of the [generated sentence](https://github.com/mozilla-iot/gateway/issues/1862).

As an aside: conceptually I always struggle with how rules work / work together:
- Is a device toggled on an event, when the value first reaches the new situation?
- Or is a rule checked every minute?
- Does 'while' override 'if' rules?
- What happens if two while-rules overlap, and the first rule wants to turn a light on, and the second wants to turn it off?

As with CSS, could I label a rule '!important', and then it will override the other? For example, I may have rules that turn the light on in the evening. But could a holiday rule override that and keep them turned off?

Could I create a rule that toggles other rules? For example: the 'light-turns-on-at-night-rule' is only on while the user it not on holiday?

**Comment by flatsiedatsie** [comment] 2019-05-08 15:11
Maybe it would be an idea to expand the sentence to explain that with a while-statement, the opposite rule is also generated?

`While Signal Hub is Detected 3, set Signal Hub Replay 2 to true`
could become
`While Signal Hub is Detected 3, set Signal Hub Replay 2 to true, otherwise set Signal Hub Replay 2 to false`

**Comment by kgiori** [comment] 2019-05-22 00:14
One side effect to watch out for is that if the triggered event is already set (e.g., disco ball already on but temp below 25), then when temp goes above 25 and back below 25, (using a "while" rule), the disco ball will not turn off.

**Comment by flatsiedatsie** [comment] 2019-05-22 14:08
@kgiori That's.. interesting. Why is that?

**Comment by flatsiedatsie** [comment] 2019-05-27 14:47
I guess it remembers the previous state?

**Comment by hobinjk** [comment] 2019-06-13 16:47
That's correct. The alternative here would be to special-case boolean properties as always flipping between true and false which I might as well do even though it corrupts the underlying system a bit

**Comment by mrstegeman** [comment] 2019-12-26 18:55
Duplicate of #2337

**Closed by mrstegeman** 2019-12-26 18:55 UTC
Labels: rules-engine
