### ISSUE TITLE
Need to figure out how retrieve log files under openwrt

### ISSUE THREAD

**Issue by dhylands** [mozilla-iot/gateway#1635] opened 2019-02-06 00:27 UTC
Currently, under OpenWRT, the log files are sent to logd and show up in /var/log/messages. This means that they aren't accessible via Settings->Developer->View Logs.

**Comment by mrstegeman** [comment] 2019-02-15 20:58
I _believe_ this should start working properly with 0.7. The problem is that the OpenWrt package just calls `npm start`, rather than using the `run-app.sh` script. With 0.6 and below, that script was responsible for creating the log file. With 0.7+, `winston` does it for us.

**Comment by dhylands** [comment] 2019-02-15 21:11
Yep - I have a raspberry pi openwrt image with 0.7 on it and I can see a log file in the /.mozilla-iot/log directory.

**Comment by mrstegeman** [comment] 2019-02-15 21:16
Perfect. Gonna close this.

**Closed by mrstegeman** 2019-02-15 21:16 UTC
Labels: backlog
