### ISSUE TITLE
daylight savings broke rule times

### ISSUE THREAD

**Issue by twobraids** [mozilla-iot/gateway#1709] opened 2019-03-16 16:41 UTC
Prior to Daylight Savings Time, I had a rule pinned to turn on a light at 5am.  After Daylight Savings Time started, the rule now says 6am.  This is not correct, I want the light to turn on at 5am regardless of the state of Daylight/Standard time.  

I'm assuming this is related to Issue #1428.

**Comment by mrstegeman** [comment] 2019-03-16 16:43
I believe this is a duplicate of #808.

**Comment by twobraids** [comment] 2019-03-16 16:47
yes, it is indeed a dupe of #808.

**Closed** 2019-03-16 16:47 UTC
Labels: duplicate
