### ISSUE TITLE
Short flash of html elements on page refresh

### ISSUE THREAD

**Issue by createcandle** [mozilla-iot/gateway#2514] opened 2020-06-09 06:24 UTC
![candle_html_elements](https://user-images.githubusercontent.com/39312291/84113223-7f575680-aa2a-11ea-9c6c-216284e1034f.png)

On a page refresh this is visible for about half a second. It's not an issue, but perhaps it's easy to polish out.

**Comment by mrstegeman** [comment] 2020-06-09 16:23
Duplicate of #1193

**Closed by mrstegeman** 2020-06-09 16:23 UTC

**Comment by createcandle** [comment] 2020-08-07 06:31
I was wondering ifi this could be fixed with CSS, where the elements don't appear/fade in until after a second of two. Especially for messages like "there are no thing connected", which is on the main things page, this could be a simple fix.
