### ISSUE TITLE
Feature Request: Add IDE

### ISSUE THREAD

**Issue by rei-vilo** [mozilla-iot/gateway#710] opened 2018-02-26 13:43 UTC
During my review, I've been surprised the Project Things by Mozilla provides no environment to configure the devices.

Mundane settings like [GPIO pins](https://github.com/mozilla-iot/gpio-adapter) or name of the [HTTP remote device](https://github.com/mozilla-iot/http-on-off-adapter) requires opening a SSH connection, dig deep into the folders hierarchy and launch a command-line utility to configure them.

```
$
cd ~/mozilla-iot/gateway/tools
./config-editor.py -e gpio-adapter
./config-editor.py -e http-on-off-adapter
```

The idea is to provide a polished interface for configuring the things, similar to the interface used for the front-end.

Additionally, the configuration interface would provide some fool-proof features to ensure the settings comply with the Web of Things data model and API.

Node-RED provides a great example. See [Discussion: Scope of the Project and Re-Use of Existing Tools](https://discourse.mozilla.org/t/discussion-scope-of-the-project-and-re-use-of-existing-tools/25783).

**Comment by mrstegeman** [comment] 2018-02-26 18:01
Duplicate of #421

**Closed by mrstegeman** 2018-02-26 18:01 UTC

**Comment by rei-vilo** [comment] 2018-02-26 18:08
@mrstegeman

You might need to reword issue #421 to make it more explicit.

**Comment by mrstegeman** [comment] 2018-02-26 18:29
@rei-vilo updated

**Comment by rei-vilo** [comment] 2018-02-26 18:32
Thanks!
