### ISSUE TITLE
Gateway "attacked" the network at Dweb Camp 😅

### ISSUE THREAD

**Issue by autonome** [mozilla-iot/gateway#2038] opened 2019-07-23 18:31 UTC
I had an Rpi with the gateway image on it at Dweb Camp this last weekend... and the default config somehow hosed a chunk of the network.

@benhylau and @whyrusleeping took a look into exactly what happened, so cc'ing them for more details.

**Comment by whyrusleeping** [comment] 2019-07-23 18:33
we tried to get it to connect to the normal network, by changing the API mode. The problem was that we didnt tell it to stop being a dhcp server, or a dns server, so it kept doing those things after connecting to the wifi

**Comment by benfrancis** [comment] 2019-07-23 19:13
LOL, nice bug description. Thanks for the report.

@autonome wrote:
> the default config somehow hosed a chunk of the network.

What do you mean by hosed a chunk of the network?

@whyrusleeping wrote:
> we tried to get it to connect to the normal network, by changing the API mode.

What do you mean by API mode?

> The problem was that we didnt tell it to stop being a dhcp server, or a dns server, so it kept doing those things after connecting to the wifi

What version of the gateway were you using? No currently released version acts as a DHCP or DNS server except for the captive portal during first time setup, which shouldn't effect other networks and is shut down when a connection to an existing network is established.

If you used the provided web interface then what you described hopefully shouldn't be possible, so I'm guessing you re-configured things yourself on the command line? Users have the freedom to break the gateway (and their network) in whatever creative ways they want if using the command line, which I would argue is a feature rather than a bug ;)

If this really was the default configuration or was done through the UI, then that's a more serious problem.

**Comment by whyrusleeping** [comment] 2019-07-23 19:23
Yeah, I don't necessarily think this was a bug. I was given a raspberry pi by one person, and asked by another to make it connect to the internet a display a thing on the screen. I had no idea what else that pi was trying to do. I manually (via the CLI) took down the wlan interface and brought it back online connected to the local wifi. I'm assuming whatever software sets up the captive portal was then maybe trying to captive portal the entire network.

**Comment by benfrancis** [comment] 2019-07-23 19:44
Yep, that would do it :)

**Comment by autonome** [comment] 2019-07-24 01:22
@benfrancis Could the captive portal bits only run when in AP mode?

**Comment by benfrancis** [comment] 2019-07-24 08:10
@autonome They already do, unless you bypass the UI and manually re-configure the network on the command line, which is not something I think we could (or should) guard against. There are countless ways you could break the gateway on the command line, that's the price of being allowed root access to your own hardware.

**Comment by benfrancis** [comment] 2019-07-24 11:12
Unless I've misunderstood I don't think there's any action to take here so closing. Please comment with any further suggestions though.

**Closed by benfrancis** 2019-07-24 11:12 UTC

**Comment by autonome** [comment] 2019-07-24 22:37
👍🏼 Got it, thanks Ben!

**Comment by benhylau** [comment] 2019-07-25 08:54
Hey I am the network coordinator at DWeb Camp, and want to add some details from my perspective.  The network is a mesh network topology consisting of 6 nodes, where each one has a big LAN, and this Raspberry Pi was in one of those 6 spaces connected to an Access Point, so "hosed a chunk of the network" means taking down access to one of 6 spaces because anyone getting on the LAN is getting a non-routable IP address by the DHCP server on the Pi. The device has SSH Access off and was running DNS, which makes the activity seems potentially malicious.

When we located the Pi finally, we found it was running dnsmasq on the wlan0 interface, with dhcp-authoritative mode (which effectively overrides existing DHCP leases for clients as described in the dnsmasq warnings) and a DNS server. Not sure what state the device was in or how it got to that state, but it serves no web UI, has dnsmasq running on wlan0.

https://twitter.com/jonahedwards/status/1152664633972387840?s=19

**Comment by benfrancis** [comment] 2019-07-25 09:44
@benhylau Sorry to hear about the problems you had with your network, I imagine that caused a lot of inconvenience for people! However, it sounds like the gateway was doing exactly what it was configured to do by the user.

The Raspberry Pi image is designed to act as a captive portal during first time setup, which is why DHCP and DNS were running. SSH is off by default by design.

Unfortunately rather than configure the gateway through its first time setup UI, the user gave it to @whyrusleeping who unknowingly manually reconfigured it as a black hole.

Do let us know if there's anything you think we could improve, but it sounds like the gateway was just misconfigured. The only way I can think of to guard against that would be to not allow users access to the command line, which we're not inclined to do.

**Comment by benhylau** [comment] 2019-07-26 08:56
I agree with @benfrancis that nothing needs to be done as the manual re-configuring of wlan0 isn't something you can (or should) guard against. Thanks all for sharing their piece of the puzzle to trace the process of how this happened.

**Comment by flatsiedatsie** [comment] 2019-08-19 17:49
Something similar happened to me today. I had created a new image to test an add-on. 

Without realizing what the source was, I spent and hour trying to figure out why I could reach devices on the network, but couldn't reach anything online anymore. In the end, turning off the gateway solved the problem.
