### ISSUE TITLE
Connect input device property value to output device property

### ISSUE THREAD

**Issue by tomasy** [mozilla-iot/gateway#1528] opened 2018-12-03 18:36 UTC
Feature request
As a owner of a IKEA Trådlös Dimmer I have cretate a device Thing with a `LevelProperty` with values from 0 to 100%. The value of `LevelProperty` for this dimmer device I want to set as a value to `BrightnessProperty` for a dimmable lamp.

New feauture is requested in Rules to connect a value from an input device and set this value to an output device. 
Today I must create a rule when the dimmer has the value 0 and turn off lamp, another rule where the dimmer has value 10 and set the brightness to 10 for the lamp and so on.

Even better if it handle a transformation of values. 
Example: Input device have a value property from 0 to 100% The output device have a `ColorTemperatureProperty` from 250 to 454. If rule engine could transform 0% to 250 and 100% to 454 and the value between.

**Comment by DavidKarlas** [comment] 2018-12-22 07:41
This is duplicate of https://github.com/mozilla-iot/gateway/issues/805

**Comment by hobinjk** [comment] 2019-01-14 16:25
(closing as duplicate)

**Closed by hobinjk** 2019-01-14 16:25 UTC
