### ISSUE TITLE
Wheswell power strip

### ISSUE THREAD

**Issue by rjohn10** [mozilla-iot/gateway#1539] opened 2018-12-12 23:53 UTC
Hi,
Is there plugin available for the Wheswell power strip.  
The power strip is working with the Tuya's "Smart Life" app .
Thanks,

**Comment by mrstegeman** [comment] 2018-12-13 02:39
I can’t seem to find any open APIs for this device, so supporting it would be quite difficult.

**Comment by mrstegeman** [comment] 2019-03-12 13:14
I believe this is actually a Tuya device, so I'm going to mark this as a duplicate of #1557.

**Closed by mrstegeman** 2019-03-12 13:14 UTC
Labels: adapters, duplicate
