### ISSUE TITLE
Thing Hiding

### ISSUE THREAD

**Issue by gucci-on-fleek** [mozilla-iot/gateway#2341] opened 2019-12-03 22:50 UTC
I'm beginning to get quite a few Things in my gateway. Lots of these things aren't very useful for humans, but are helpful for rules (Pulse adapter timers, Philips Hue Switches). It would be nice to be able to hide them from the Things page and from the Floorplan. Right now, I'm just moving them to the end, but it's still slightly annoying. 
![image](https://user-images.githubusercontent.com/49086429/70096208-c714a580-15e3-11ea-9df8-5a9016fac2ae.png) 
![image](https://user-images.githubusercontent.com/49086429/70096222-ce3bb380-15e3-11ea-8d70-3332c84483ca.png)
In the floorplan view, I'm beginning to run out of room to put any more things, so I'm just putting the "useless" ones off to the side. I could delete the Things, but then I couldn't use them in rules and they would keep showing up every time that I added new Things. It would be nice if I could check a "hidden" box so that it wouldn't show up unless I looked for it specifically (perhaps under a folder in the Things tab).

**Comment by mrstegeman** [comment] 2019-12-03 22:54
Duplicate of #1191 and #1814

**Closed by mrstegeman** 2019-12-03 22:54 UTC

**Comment by gucci-on-fleek** [comment] 2019-12-03 23:29
@mrstegeman #1814 is closed with the solution being a dashboard view. I may be mistaken, but isn't that the Floorplan view? Either way, it doesn't appear that hiding things from the Floorplan view has been discussed. I can see some problems with hiding things from the Things view (where would they go?), but a simple toggle to remove them from the just floorplan would still be nice. 
![image](https://user-images.githubusercontent.com/49086429/70098696-fdedba00-15e9-11ea-9fd5-fabb13fa8448.png)
Something like that, perhaps?

**Comment by mrstegeman** [comment] 2019-12-03 23:48
@benfrancis thoughts?

**Comment by flatsiedatsie** [comment] 2019-12-05 13:56
A more long-term solution could be to create a per-thing settings page. It could be an expansion of the 'edit' option.

**Comment by benfrancis** [comment] 2019-12-09 11:38
I agree that a Thing Settings view via the overflow menu (in addition to or instead of the edit view) would be a good direction. https://github.com/mozilla-iot/gateway/issues/2357
