### ISSUE TITLE
Rules - map variables to each other?

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1863] opened 2019-05-07 13:39 UTC
This may be a little far out, but I'd be curious if there are any ways to generate this functionality.

- I have a device with a humidity sensor ( between 0 and 100% ).
- I have a device with a servo that can rotate ( between 0 and 100% )

I'd like to map the value of the first to the value of the second, so that when the first one changes, the second one follows. For example, if I glue a little paper arrow to the servo I could make an analog data dashboard.

This functionality could be used in many more situations though.
- Turn an air fan higher the warmer/dustier it gets.
- Turn a light brighter the darker it gets.

A user may also want to invert this.
- Increase the speed of the bubble blowing machine the less people are in the room.

Thinking out loud, a hack might be to create 10 rules, each going something like:
`if humidity > 90, then set servo to 95%`
`if humidty > 80, then set servo to 85%`
etc

![mapping-vars](https://user-images.githubusercontent.com/805405/57303388-be4f0600-70cc-11e9-8460-27bac000d4f8.png)

I'd be curious if functionality like this would be interesting, or if it would just complicate things (pun intended).

**Comment by mrstegeman** [comment] 2019-05-07 14:42
I believe this is a duplicate of #805.

**Closed by mrstegeman** 2019-05-07 14:42 UTC
