### ISSUE TITLE
If *not* rule or how to two-way-bind

### ISSUE THREAD

**Issue by LukasVice** [mozilla-iot/gateway#1938] opened 2019-06-13 11:16 UTC
Hi,

I'm not sure if that's the correct place to ask...

I can control my Harmony Hub with the WebThings Gateway. The Harmony Hub has a property for the scene (TV, MediaCenter, Music, ...). This property is shown as a dropdown list on the web interface.
Additionally, I have a simple Moddable OnOffSwitch. Now I would like to toggle one specific scene with this OnOffSwitch. For this, I added two rules: If OnOffSwitch is set, then set scene to TV; If OnOffSwitch is unset, then set scene to "off"). This works as expected.
But since I can control the scene with the Harmony Remote, I would also like to see this "external" state change on the OnOffSwitch. Rule: If scene is TV, then set OnOffSwitch to on. But there's no possibility to add this rule: If scene is **not** TV, then set OnOffSwitch to off.
The "while" rules also don't work as expected (While scene is TV, set OnOffSwitch to on; While OnOffSwitch is on, set scene to TV) - I think it's because of https://github.com/mozilla-iot/gateway/issues/1864#issuecomment-494604798

So, what I would like to achieve is: Control one specific scene from my OnOffSwitch and always see the correct state of this specific scene on the OnOffSwitch, even if the scene is changed by the Harmony Remote.

Thank you.

**Comment by benfrancis** [comment] 2019-06-14 11:28
I would expect a rule like "While scene is TV, set OnOffSwitch to on" to work, but I have experienced some edge cases. Perhaps @hobinjk can comment?

**Comment by mrstegeman** [comment] 2019-12-26 18:55
Seems like a duplicate of #2337.

**Closed by mrstegeman** 2019-12-26 18:55 UTC
Labels: question, rules-engine
