### ISSUE TITLE
Add tiiwee support (if possible)

### ISSUE THREAD

**Issue by sindastra** [mozilla-iot/gateway#2069] opened 2019-08-08 17:04 UTC
I have battery powered door sensors by tiiwee, they communicate wirelessly with the tiiwee "base station". Sadly I don't know what standard they communicate in, but it would be great to somehow be able to add those sensors to the mozilla IoT gateway.

If anyone knows anything about tiiwee or how I could figure out what standard (if at all) they use, I'd be willing to help.

PS I also have the tiiwee remote control and the "base station" (the alarm device) and I'd be willing to disassemble them.

**Comment by sindastra** [comment] 2019-08-08 17:11
I just found this info about the radio communication tiiwee uses:

```
Wireless system - 433Mhz frequency
Completely battery powered
Up to 50 meters' range, uninterrupted
Up to 25 meters' range, inside home depending on wall infrastructure
```

If anyone knows a standard with those properties, any info would be welcome.

**Comment by mrstegeman** [comment] 2019-08-08 17:12
This is probably a duplicate of #682, in that case.

**Comment by sindastra** [comment] 2019-08-08 17:15
@mrstegeman Could very well be. A quick online lookup revealed that a lot of devices seem to use the 433 MHz frequency.

Here is the tiiwee product page: [EXTERNAL LINK](https://www.tiiwee.com/collections/home-alarm-kits/products/tiiwee-home-alarm-system-starter-kit-wireless-burglar-alarm-system-with-siren-unit-2-window-door-sensors-and-remote-control-expandable-alarm-and-chime-mode-home-security)

**Comment by mrstegeman** [comment] 2019-08-08 17:16
I'm going to close this in favor of the more generic adapter. From what @kgiori has told me, there is a pretty small set of commands that all these devices tend to use.

**Closed by mrstegeman** 2019-08-08 17:16 UTC
Labels: adapters

**Comment by sindastra** [comment] 2019-08-08 17:25
Thanks, I did not find #682 at first. Will continue there. 👍

**Comment by tim-hellhake** [comment] 2019-08-11 22:06
@sindastra I bought a few tiiwee sensors.
As @mrstegeman suspected it's the standard 433MHz protocol.

**Comment by sindastra** [comment] 2019-08-11 22:15
@tim-hellhake I bought off the shelf parts and built a receiver and I can confirm tiiwee  signals can be received.

**Comment by sindastra** [comment] 2019-08-11 22:35
> You can try out my rf433 addon when it's finished.

May I ask what your idea is/plans are for the add-on?

**Comment by tim-hellhake** [comment] 2019-08-11 22:42
I connected a 433 MHz receiver to a pin of my pi. I already managed to receive the transmissions from the window contact.
You can see the code here: https://github.com/tim-hellhake/rf433-adapter
