### ISSUE TITLE
Choose a main property for a thing

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/gateway#1907] opened 2019-05-23 07:49 UTC
![weird-central-item](https://user-images.githubusercontent.com/805405/58234359-d90cb600-7d2d-11e9-8ca0-48cac9235cf8.gif)

In the above GIF there are two properties:
- The top right toggle is a read only OnOffSwitch OnOff property, and indicates when the heating element is actually heating.
- The bottom right toggle is a SmartPlug type OnOff property, which sets the entire 'smart' heater to an active or disabled state.

in the animation I'm trying to get the top-right read-only thermostat toggle to show in the highlighted area, so that I can tell if the heater is curren;y heating. But as you can tell it always seems to show the 'power' property's value.

Here is the code that generated the properties:

```
                if new_sub_type == 2: #V_status
                    self._type.append('OnOffSwitch')
                    self.properties[targetPropertyID] = MySensorsProperty(
                        self,
                        targetPropertyID,
                        {
                            '@type': 'OnOffProperty',
                            'label': new_description,
                            'type': 'boolean',
                            'readOnly': True,
                        },
                        new_value, new_node_id, new_child_id, new_sub_type)
```

The power property code:
```
            elif child.type == 3:                       # Binary
                if new_sub_type == 2: # V_STATUS
                    self._type.append('SmartPlug')           
                    self.properties[targetPropertyID] = MySensorsProperty(
                        self,
                        targetPropertyID,
                        {
                            '@type': 'OnOffProperty',
                            'label': new_description,
                            'type': 'boolean',
                        },
                        new_value, new_node_id, new_child_id, new_sub_type)
```

Perhaps I'm conceptualizing it wrong?

Perhaps I implemented it wrong, and the problem is that the thing has multiple types appended to it? In this case "OnOffSwitch" and "SmartPlug" at the same time?

**Comment by mrstegeman** [comment] 2019-05-23 13:35
The problem is that the UI doesn't know how to distinguish between the two `OnOffProperty`s. To make the UI play nicely, just remove the `@type` from the non-dominant one.

**Comment by flatsiedatsie** [comment] 2019-05-23 16:37
But the MySensors add-on can't decide for all users which property they care about most / which should gain dominance?

Wouldn't a better solution be to fix it so that the UI can distinguish them?

This would also explain why changing to another item in the dropdown never worked for me. 

One solution might be to let the user select which item should be dominant? I created this proposal for that:
https://github.com/mozilla-iot/gateway/issues/1826

**Comment by benfrancis** [comment] 2019-05-24 15:15
Duplicate of #1826

**Closed by benfrancis** 2019-05-24 15:15 UTC
Labels: ui-needed
