### ISSUE TITLE
Adjust automatically for daylight savings time changes

### ISSUE THREAD

**Issue by benfrancis** [mozilla-iot/gateway#2240] opened 2019-10-28 12:59 UTC
As a user I want my rules to automatically update when daylight savings time changes so that I don't have to manually shift all my rules by one hour twice a year

**Comment by benfrancis** [comment] 2019-10-28 13:04
See also https://discourse.mozilla.org/t/weird-summer-time-behaviour/47563/2

**Comment by mrstegeman** [comment] 2019-10-28 16:17
This is actually a duplicate of #808, and should be fixed by #2227.

**Closed by mrstegeman** 2019-10-28 16:17 UTC
Labels: story
