### ISSUE TITLE
Problem with Eve Energy

### ISSUE THREAD

**Issue by idahuang-temboo** [mozilla-iot/gateway#1462] opened 2018-10-29 20:07 UTC
Download 0.6.1, flashed it on SD card and now running on PI
Unable to find and connect to this device. 
![screen shot 2018-10-29 at 4 06 32 pm](https://user-images.githubusercontent.com/42546754/47677149-bc900d00-db94-11e8-853b-6fa980343796.png)
![screen shot 2018-10-29 at 4 06 25 pm](https://user-images.githubusercontent.com/42546754/47677151-bdc13a00-db94-11e8-886b-612ef64e9aaf.png)

**Comment by mrstegeman** [comment] 2018-10-29 20:27
In order to use the Eve Energy, you'll need to install the HomeKit adapter through _Settings -> Add-ons -> +_.

After doing so, your device will **hopefully** be displayed on the "Add Things" screen you've shown above.

**Comment by idahuang-temboo** [comment] 2018-10-30 13:42
![screen shot 2018-10-29 at 5 59 58 pm](https://user-images.githubusercontent.com/42546754/47722183-29a0b280-dc28-11e8-8d7e-7ec5cb38d82a.png)

**Comment by mrstegeman** [comment] 2018-10-30 14:03
We seem to have some pairing issues with Bluetooth that I can't currently reproduce, unfortunately.

I'm going to mark this as a duplicate of #1435, which is the same issue.

**Closed by mrstegeman** 2018-10-30 14:03 UTC

**Comment by idahuang-temboo** [comment] 2018-10-30 14:17
[run-app.txt](https://github.com/mozilla-iot/gateway/files/2529992/run-app.txt)

**Comment by idahuang-temboo** [comment] 2018-10-30 14:28
@mrstegeman 
How are you guys able to pair with the Eve Energy? I'm using a external bluetooth scanning tool like Bluetility to connect to this device. I can connect to it but not pair with the device which I believe is necessary to read the values from certain characteristics. I'm interested in reading UUID 00000026-0000-1000-8000-0026BB765291 which tells me if the outlet is in use or not.

**Comment by idahuang-temboo** [comment] 2018-10-30 14:38
@mrstegeman 
https://github.com/mozilla-iot/homekit-adapter/blob/5950121293e61a86b2b5953ba178e589a525d54a/lib/homekit-device.js

I see you called device.pair(pin) and here is the function definition I found. I'm not too familiar with javascript. Could you explain what you guys are doing here? Is this the only thing necessary to pair setup and verify?

Thanks!

**Comment by mrstegeman** [comment] 2018-10-30 14:40
@idahuang-temboo We use a library I wrote to do all of the IP and BLE communications: https://www.npmjs.com/package/hap-controller
